### ISSUE TITLE
ImportError: cannot import name 'KerberosUserEnum' from 'minikerberos.security'

### ISSUE THREAD

**Issue by the-grizzly-bear** [skelsec/kerberoast#14]
erberoast ldap spn <my ip>
Traceback (most recent call last):
  File "/usr/local/bin/kerberoast", line 33, in <module>
    sys.exit(load_entry_point('kerberoast==0.2.0', 'console_scripts', 'kerberoast')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/bin/kerberoast", line 25, in importlib_load_entry_point
    return next(matches).load()
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 202, in load
    module = import_module(match.group('module'))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/user/.local/lib/python3.11/site-packages/kerberoast/kerberoast.py", line 15, in <module>
    from minikerberos.security import KerberosUserEnum, APREPRoast, Kerberoast
ImportError: cannot import name 'KerberosUserEnum' from 'minikerberos.security' (/home/user/.local/lib/python3.11/site-packages/minikerberos/security.py)

**Comment by chosenonehacks** [comment]
I had the same issue after installing with pip3 install kerberoast

**Comment by cowsaymoe** [comment]
The issue is not with kerberoast, but a dependency minikerberos. Solved by downgrading https://github.com/skelsec/pypykatz/issues/117#issuecomment-1433593989
